export const actionTypes = {
    DATA_REQUESTED: 'DATA_REQUESTED',
    DATA_PROCESSING: 'DATA_PROCESSING',
    DATA_LOADED: 'DATA_LOADED',
    STAGE_SEARCH_CRITERIA: 'STAGE_SEARCH_CRITERIA',
    GET_PERSISTED_DATA: 'GET_PERSISTED_DATA',
    USER_DETAILS_REQUESTED: 'USER_DETAILS_REQUESTED',
    USER_DETAILS_PROCESSING: 'USER_DETAILS_PROCESSING',
    USER_DETAILS_LOADED: 'USER_DETAILS_LOADED'
} 