export const actionTypes = {
    DATA_REQUESTED: 'DATA_REQUESTED',
    DATA_PROCESSING: 'DATA_PROCESSING',
    DATA_LOADED: 'DATA_LOADED',
    STAGE_SEARCH_CRITERIA: 'STAGE_SEARCH_CRITERIA',
    GET_PERSISTED_DATA: 'GET_PERSISTED_DATA'
} 